{% set name = "langchain-azure-dynamic-sessions" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langchain_azure_dynamic_sessions-{{ version }}.tar.gz
  sha256: 9316a67fd9ad8f199b2a181bd62712e6561a4a0ae83db8ccf12577a6766d25dd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - langchain-core <0.4.0,>=0.3.0
    - azure-identity >=1.16.0,<2.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - langchain_azure_dynamic_sessions
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/langchain-ai/langchain
  summary: An integration package connecting Azure Container Apps dynamic sessions and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
